import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";


import { Footer } from "@/layouts/footer/footer";
import { Header } from "@/layouts/header/header";

const internItelic = localFont({
  src: "./fonts/intern/Inter-Italic-VariableFont_opsz,wght.ttf",
  variable: "--fonnt-inter-itelic",
  weight: "100 900",
});
const internFont = localFont({
  src: "./fonts/intern/Inter-VariableFont_opsz,wght.ttf",
  variable: "--fonnt-inter-regular",
  weight: "100 900",
});
const ibnsansBold = localFont({
  src: "./fonts/ibnsans/IBMPlexSans-Bold.ttf",
  variable: "--font-ibnsansBold",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "StepSync",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${internItelic.variable} ${internFont.variable} ${ibnsansBold.variable}`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
